import { MigrationInterface, QueryRunner } from "typeorm";

export class InitSchema1777435914241 implements MigrationInterface {
    name = 'InitSchema1777435914241'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "formulas" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "seller_id" uuid NOT NULL, "name" character varying(100) NOT NULL, "expression" jsonb NOT NULL, CONSTRAINT "PK_deb92fee98f29de4b5d31406823" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_269386680695ad49b92c0ca9e1" ON "formulas" ("seller_id", "name") `);
        await queryRunner.query(`CREATE TYPE "public"."usage_records_status_enum" AS ENUM('open', 'closed')`);
        await queryRunner.query(`CREATE TABLE "usage_records" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "seller_id" uuid NOT NULL, "name" character varying(200) NOT NULL, "link_token" character varying NOT NULL, "status" "public"."usage_records_status_enum" NOT NULL DEFAULT 'open', CONSTRAINT "UQ_a77bbbae8148f76c1c47ccc47f5" UNIQUE ("link_token"), CONSTRAINT "PK_e511cf9f7dc53851569f87467a5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_a77bbbae8148f76c1c47ccc47f" ON "usage_records" ("link_token") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_265f745874f052c305e705c822" ON "usage_records" ("seller_id", "name") `);
        await queryRunner.query(`CREATE TYPE "public"."submissions_status_enum" AS ENUM('pending', 'approved', 'discarded', 'manual')`);
        await queryRunner.query(`CREATE TABLE "submissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "usage_record_id" uuid NOT NULL, "buyer_id" uuid NOT NULL, "electricity_current" numeric(10,2), "water_current" numeric(10,2), "photo_urls" jsonb, "status" "public"."submissions_status_enum" NOT NULL DEFAULT 'pending', "submitted_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_10b3be95b8b2fb1e482e07d706b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_20cad70bfb903bfc3d2f052400" ON "submissions" ("usage_record_id", "buyer_id") `);
        await queryRunner.query(`CREATE TYPE "public"."replacement_requests_type_enum" AS ENUM('electricity', 'water')`);
        await queryRunner.query(`CREATE TABLE "replacement_requests" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "seller_id" uuid NOT NULL, "buyer_id" uuid NOT NULL, "type" "public"."replacement_requests_type_enum" NOT NULL, "old_reading" numeric(10,2) NOT NULL, "new_reading" numeric(10,2) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5a0d173cb73f2cda890c59bd05c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."sheet_config_columns_column_type_enum" AS ENUM('system_field', 'custom')`);
        await queryRunner.query(`CREATE TYPE "public"."sheet_config_columns_system_field_key_enum" AS ENUM('people_count', 'room_price', 'electricity_old', 'electricity_new', 'electricity_used', 'water_old', 'water_new', 'water_used')`);
        await queryRunner.query(`CREATE TABLE "sheet_config_columns" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "sheet_config_id" uuid NOT NULL, "column_order" integer NOT NULL, "column_type" "public"."sheet_config_columns_column_type_enum" NOT NULL, "system_field_key" "public"."sheet_config_columns_system_field_key_enum", "label" character varying(200) NOT NULL, "variable_id" uuid, "formula_id" uuid, "dummy_value" numeric(15,2) NOT NULL DEFAULT '0', CONSTRAINT "PK_cab252a4893e915eb2dccba1ef7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sheet_configs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "seller_id" uuid NOT NULL, "name" character varying(200) NOT NULL, CONSTRAINT "PK_1f5c13e852df12013d724483d42" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_9a77486e16e11cd9b989b1d5d2" ON "sheet_configs" ("seller_id", "name") `);
        await queryRunner.query(`CREATE TABLE "bill_line_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "bill_id" uuid NOT NULL, "column_order" integer NOT NULL, "label" character varying(200) NOT NULL, "value" numeric(15,2) NOT NULL, CONSTRAINT "PK_791329c8eacdb7ed615d6c13807" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."payments_status_enum" AS ENUM('pending', 'paid', 'failed', 'refunded')`);
        await queryRunner.query(`CREATE TABLE "payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "bill_id" uuid NOT NULL, "amount" numeric(15,2) NOT NULL, "status" "public"."payments_status_enum" NOT NULL DEFAULT 'pending', "paid_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_197ab7af18c93fbb0c9b28b4a59" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "bills" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "seller_id" uuid NOT NULL, "buyer_id" uuid NOT NULL, "name" character varying(200) NOT NULL, "billing_cycle" character varying(7) NOT NULL, "sheet_config_id" uuid, "usage_record_id" uuid, "reference_record_id" uuid, "electricity_replacement_id" uuid, "water_replacement_id" uuid, "snapshot_people_count" integer NOT NULL, "snapshot_room_price" numeric(15,2) NOT NULL, "total_amount" numeric(15,2), "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a56215dfcb525755ec832cc80b7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_129680a1b07fe8c80e1f750587" ON "bills" ("seller_id", "created_at") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_c6befc59f6b5cc7bec61db0e90" ON "bills" ("buyer_id", "billing_cycle") `);
        await queryRunner.query(`CREATE TABLE "buyers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "seller_id" uuid NOT NULL, "username" character varying(100) NOT NULL, "password_hash" character varying NOT NULL, "full_name" character varying(200) NOT NULL, "phone" character varying(20), "people_count" integer NOT NULL, "room_price" numeric(15,2) NOT NULL, "formula_id" uuid, CONSTRAINT "UQ_e06799f9748a1a844fc8fa6492e" UNIQUE ("username"), CONSTRAINT "PK_aff372821d05bac04a18ff8eb87" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_1fef1fc6690cf1c1e7dcd5393d" ON "buyers" ("seller_id", "full_name") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e06799f9748a1a844fc8fa6492" ON "buyers" ("username") `);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('admin', 'seller')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "username" character varying(100) NOT NULL, "password_hash" character varying NOT NULL, "role" "public"."users_role_enum" NOT NULL, "full_name" character varying(200), "phone" character varying(20), "email" character varying(200), "address" text, "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_fe0bb3f6520ee0469504521e71" ON "users" ("username") `);
        await queryRunner.query(`CREATE TABLE "variables" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "seller_id" uuid NOT NULL, "name" character varying(100) NOT NULL, "description" text, CONSTRAINT "PK_395ef5737c2bfc06e701bd2f7e8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_44d43785e51349be1ed1b54c1a" ON "variables" ("seller_id", "name") `);
        await queryRunner.query(`CREATE TYPE "public"."audit_logs_actor_type_enum" AS ENUM('admin', 'seller', 'buyer')`);
        await queryRunner.query(`CREATE TYPE "public"."audit_logs_action_enum" AS ENUM('create', 'update', 'delete', 'approve', 'discard', 'close', 'export')`);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" BIGSERIAL NOT NULL, "actor_type" "public"."audit_logs_actor_type_enum" NOT NULL, "actor_id" uuid NOT NULL, "action" "public"."audit_logs_action_enum" NOT NULL, "target_type" character varying(100) NOT NULL, "target_id" uuid NOT NULL, "metadata" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a358c00ae08bdea24880372d7a" ON "audit_logs" ("target_type", "target_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_4a85d553dbb4006bd350ab6f88" ON "audit_logs" ("actor_id", "created_at") `);
        await queryRunner.query(`ALTER TABLE "formulas" ADD CONSTRAINT "FK_aad652dfec447b50979aa7ac165" FOREIGN KEY ("seller_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "usage_records" ADD CONSTRAINT "FK_20e52ab0d634e58f7dcbcea3f56" FOREIGN KEY ("seller_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "submissions" ADD CONSTRAINT "FK_c7fbfe0597bc0317df92e589d36" FOREIGN KEY ("usage_record_id") REFERENCES "usage_records"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "submissions" ADD CONSTRAINT "FK_ead14589339fc795ae0b259f349" FOREIGN KEY ("buyer_id") REFERENCES "buyers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "replacement_requests" ADD CONSTRAINT "FK_09061f333c316ff10bd12e9fb3e" FOREIGN KEY ("seller_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "replacement_requests" ADD CONSTRAINT "FK_9501233982834cc1e235f32a17a" FOREIGN KEY ("buyer_id") REFERENCES "buyers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sheet_config_columns" ADD CONSTRAINT "FK_8aa9a1e7019b3fcf9fd277bd416" FOREIGN KEY ("sheet_config_id") REFERENCES "sheet_configs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sheet_config_columns" ADD CONSTRAINT "FK_2528b2a78667183692c2a0515b2" FOREIGN KEY ("variable_id") REFERENCES "variables"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sheet_config_columns" ADD CONSTRAINT "FK_bd47d724085e1deb976b03a082d" FOREIGN KEY ("formula_id") REFERENCES "formulas"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sheet_configs" ADD CONSTRAINT "FK_4f30a2059b85e05e67f6ac35b8e" FOREIGN KEY ("seller_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bill_line_items" ADD CONSTRAINT "FK_711991fa405e2ae72dfade49cb5" FOREIGN KEY ("bill_id") REFERENCES "bills"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_66f88f551e1a401fd8f84eb8bc5" FOREIGN KEY ("bill_id") REFERENCES "bills"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bills" ADD CONSTRAINT "FK_c1d678450ecb9da1180a11d4db9" FOREIGN KEY ("seller_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bills" ADD CONSTRAINT "FK_df4600972f0ffd5a2279d7a9f5f" FOREIGN KEY ("buyer_id") REFERENCES "buyers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bills" ADD CONSTRAINT "FK_9f82c0f879cd930e7e2323c595e" FOREIGN KEY ("sheet_config_id") REFERENCES "sheet_configs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bills" ADD CONSTRAINT "FK_b8f6ac9bf2f6a7572689a752400" FOREIGN KEY ("usage_record_id") REFERENCES "usage_records"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bills" ADD CONSTRAINT "FK_04c1e2665a2b06544cb6e5dfba7" FOREIGN KEY ("reference_record_id") REFERENCES "usage_records"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bills" ADD CONSTRAINT "FK_a07373231e618dbf94f17c3f4f8" FOREIGN KEY ("electricity_replacement_id") REFERENCES "replacement_requests"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bills" ADD CONSTRAINT "FK_7fa0ba7912d64af914ec8592a8b" FOREIGN KEY ("water_replacement_id") REFERENCES "replacement_requests"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "buyers" ADD CONSTRAINT "FK_459caadb8b8481fc85073aa1e98" FOREIGN KEY ("seller_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "buyers" ADD CONSTRAINT "FK_f0b936c8d012da4f6220277e65f" FOREIGN KEY ("formula_id") REFERENCES "formulas"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "variables" ADD CONSTRAINT "FK_3e7068df77d1b700f65830e1e13" FOREIGN KEY ("seller_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "variables" DROP CONSTRAINT "FK_3e7068df77d1b700f65830e1e13"`);
        await queryRunner.query(`ALTER TABLE "buyers" DROP CONSTRAINT "FK_f0b936c8d012da4f6220277e65f"`);
        await queryRunner.query(`ALTER TABLE "buyers" DROP CONSTRAINT "FK_459caadb8b8481fc85073aa1e98"`);
        await queryRunner.query(`ALTER TABLE "bills" DROP CONSTRAINT "FK_7fa0ba7912d64af914ec8592a8b"`);
        await queryRunner.query(`ALTER TABLE "bills" DROP CONSTRAINT "FK_a07373231e618dbf94f17c3f4f8"`);
        await queryRunner.query(`ALTER TABLE "bills" DROP CONSTRAINT "FK_04c1e2665a2b06544cb6e5dfba7"`);
        await queryRunner.query(`ALTER TABLE "bills" DROP CONSTRAINT "FK_b8f6ac9bf2f6a7572689a752400"`);
        await queryRunner.query(`ALTER TABLE "bills" DROP CONSTRAINT "FK_9f82c0f879cd930e7e2323c595e"`);
        await queryRunner.query(`ALTER TABLE "bills" DROP CONSTRAINT "FK_df4600972f0ffd5a2279d7a9f5f"`);
        await queryRunner.query(`ALTER TABLE "bills" DROP CONSTRAINT "FK_c1d678450ecb9da1180a11d4db9"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_66f88f551e1a401fd8f84eb8bc5"`);
        await queryRunner.query(`ALTER TABLE "bill_line_items" DROP CONSTRAINT "FK_711991fa405e2ae72dfade49cb5"`);
        await queryRunner.query(`ALTER TABLE "sheet_configs" DROP CONSTRAINT "FK_4f30a2059b85e05e67f6ac35b8e"`);
        await queryRunner.query(`ALTER TABLE "sheet_config_columns" DROP CONSTRAINT "FK_bd47d724085e1deb976b03a082d"`);
        await queryRunner.query(`ALTER TABLE "sheet_config_columns" DROP CONSTRAINT "FK_2528b2a78667183692c2a0515b2"`);
        await queryRunner.query(`ALTER TABLE "sheet_config_columns" DROP CONSTRAINT "FK_8aa9a1e7019b3fcf9fd277bd416"`);
        await queryRunner.query(`ALTER TABLE "replacement_requests" DROP CONSTRAINT "FK_9501233982834cc1e235f32a17a"`);
        await queryRunner.query(`ALTER TABLE "replacement_requests" DROP CONSTRAINT "FK_09061f333c316ff10bd12e9fb3e"`);
        await queryRunner.query(`ALTER TABLE "submissions" DROP CONSTRAINT "FK_ead14589339fc795ae0b259f349"`);
        await queryRunner.query(`ALTER TABLE "submissions" DROP CONSTRAINT "FK_c7fbfe0597bc0317df92e589d36"`);
        await queryRunner.query(`ALTER TABLE "usage_records" DROP CONSTRAINT "FK_20e52ab0d634e58f7dcbcea3f56"`);
        await queryRunner.query(`ALTER TABLE "formulas" DROP CONSTRAINT "FK_aad652dfec447b50979aa7ac165"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4a85d553dbb4006bd350ab6f88"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a358c00ae08bdea24880372d7a"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP TYPE "public"."audit_logs_action_enum"`);
        await queryRunner.query(`DROP TYPE "public"."audit_logs_actor_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_44d43785e51349be1ed1b54c1a"`);
        await queryRunner.query(`DROP TABLE "variables"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fe0bb3f6520ee0469504521e71"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e06799f9748a1a844fc8fa6492"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1fef1fc6690cf1c1e7dcd5393d"`);
        await queryRunner.query(`DROP TABLE "buyers"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c6befc59f6b5cc7bec61db0e90"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_129680a1b07fe8c80e1f750587"`);
        await queryRunner.query(`DROP TABLE "bills"`);
        await queryRunner.query(`DROP TABLE "payments"`);
        await queryRunner.query(`DROP TYPE "public"."payments_status_enum"`);
        await queryRunner.query(`DROP TABLE "bill_line_items"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9a77486e16e11cd9b989b1d5d2"`);
        await queryRunner.query(`DROP TABLE "sheet_configs"`);
        await queryRunner.query(`DROP TABLE "sheet_config_columns"`);
        await queryRunner.query(`DROP TYPE "public"."sheet_config_columns_system_field_key_enum"`);
        await queryRunner.query(`DROP TYPE "public"."sheet_config_columns_column_type_enum"`);
        await queryRunner.query(`DROP TABLE "replacement_requests"`);
        await queryRunner.query(`DROP TYPE "public"."replacement_requests_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_20cad70bfb903bfc3d2f052400"`);
        await queryRunner.query(`DROP TABLE "submissions"`);
        await queryRunner.query(`DROP TYPE "public"."submissions_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_265f745874f052c305e705c822"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a77bbbae8148f76c1c47ccc47f"`);
        await queryRunner.query(`DROP TABLE "usage_records"`);
        await queryRunner.query(`DROP TYPE "public"."usage_records_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_269386680695ad49b92c0ca9e1"`);
        await queryRunner.query(`DROP TABLE "formulas"`);
    }

}
